// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// ✅ Load Inter from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // Regular + Bold
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
